"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import EMAIL_BACKEND

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

import os
from dotenv import load_dotenv
load_dotenv()
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!

#新增404必须把debug改成false
DEBUG = True
#这里也要改，把空改了
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',#新增
    'captcha',#验证码
    'social_django',#第三方登录
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #测试csrf先关闭，平常要打开
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #新增ACL访问控制中间件，必须在Auth认证后面
    'mysite.middleware.ACLMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    #点击劫持有关
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #由于写了最外层的templates，这里要从空的改成下面
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #为了使用{% url 'social:begin'...%}
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD':os.getenv('DB_PASSWORD'),

        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4'
        },
        'CONN_MAX_AGE': 60
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py 末尾添加
# 验证码配置，调整清晰度和复杂度
CAPTCHA_LENGTH = 4  # 字符数，默认是4，不用改
CAPTCHA_FONT_SIZE = 32  # 字体大小，调大一点看得更清楚
CAPTCHA_IMAGE_SIZE = (120, 50)  # 图片宽高，调宽一点
CAPTCHA_LETTER_ROTATION = (-15, 15)  # 减少字符旋转角度，不那么歪
CAPTCHA_NOISE_FUNCTIONS = (
    'captcha.helpers.noise_dots',  # 只保留点干扰，去掉线条干扰
)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  # 白色背景，对比更强
CAPTCHA_FOREGROUND_COLOR = '#000000'  # 黑色字符，更清晰
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # 纯随机字符，不用数学题
CAPTCHA_REFRESH_BUTTON = True  # 保留刷新按钮，看不清可以换一张
CAPTCHA_TEXT = "看不清？换一张"  # 刷新按钮改成中文

#redis缓存配置
CACHES={
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":os.getenv('REDIS_URL'),
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS":{
                "max_connections":100,
            },
        }
    },
    #新增session会话专用缓存
    "session_cache":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":os.getenv('REDIS_SESSION_URL'),
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS":{
                "max_connections":100,
            },
        }
    },

}
"""
写了这个不能实现第三方登录
#新增sessions会话引擎:缓存+数据库双写
SESSION_ENGINE='django.contrib.sessions.backends.cached_db'
#指定会话使用上面单独定义的session_cache缓存
SESSION_CACHE_ALIAS='session_cache'
#会话基础参数
SESSION_COOKIE_AGE=3600 #1小时过期
#每次访问刷新过期时间
SESSION_SAVE_EVERY_REQUEST=False
SESSION_COOKIE_NAME="session_id"

SESSION_EXPIRE_AT_BROWSER_CLOSE=False
"""

#celery的配置
CELERY_BROKER_URL=os.getenv('CELERY_BROKER_URL')
#暂时不存结果
CELERY_RESULT_BACKEND=None
CELERY_ACCEPT_CONTENT=['json']
CELERY_TASK_SERIALIZER='json'
CELERY_RESULT_SERIALIZER='json'
CELERY_TIMEZONE='Asia/Shanghai'



EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.qq.com'
EMAIL_PORT=465
EMAIL_HOST_USER=os.getenv('EMAIL_HOST_USER')
#这是授权码
EMAIL_HOST_PASSWORD=os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL=True
EMAIL_USE_TLS=False
DEFAULT_FROM_EMAIL=os.getenv('DEFAULT_FROM_EMAIL')

#celery定时任务
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE={
    #自定义任务名称
    'test-every-minute':{
        'task':'myapp.tasks.print_time_task',
        'schedule':crontab(minute='*/1'),
    },
}

#GitHub OAuth2后端
AUTHENTICATION_BACKENDS={
    'social_core.backends.github.GithubOAuth2',
    #django默认的用户认证后端（必须保留，否则本地账号登录会失效
    'django.contrib.auth.backends.ModelBackend',
}

#替换注册的OAuth App得到的ClientID
SOCIAL_AUTH_GITHUB_KEY=os.getenv('SOCIAL_AUTH_GITHUB_KEY')
#替换对应的 Client Secret
SOCIAL_AUTH_GITHUB_SECRET=os.getenv('SOCIAL_AUTH_GITHUB_SECRET')


#跳转配置
#登录成功后跳转到哪一个界面
SOCIAL_AUTH_LOGIN_REDIRECT_URL='/index'
#未登录时访问要登录的界面，会跳转这个地址
SOCIAL_AUTH_LOGIN_URL='/'
#退出登录的界面(也可以不写)
SOCIAL_AUTH_LOGOUT_URL='/'

#写这个未登录会跳转到/
LOGIN_URL='/'