# Generated by Django 6.0.6 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('status', models.CharField(default='open', max_length=20)),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务表',
                'permissions': [('close_task', '关闭任务')],
            },
        ),
    ]
