# Generated by Django 6.0.6 on 2026-06-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_testproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testproduct',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
