# Generated by Django 6.0.6 on 2026-06-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_data_created_testproduct_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testproduct',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
